### ISSUE TITLE
rev and loop demos crash

### ISSUE THREAD

**Issue by kfish** [jaspervdj/turnstyle#1]
pi works fine for me, but rev and loop crash with error:

Interpreter crashed: TypeError: this.lhs.freeVars(...).union is not a function

(There's nothing in my Chrome devtools  console, let me know if you need any other info)

**Comment by jaspervdj** [comment]
@kfish Thanks for opening this! It works fine for me in chrome and firefox.  What browser version / OS are you using?

**Comment by kfish** [comment]
Yes that fixes it, thanks!
